CP-4 Add new functionality
githubTestUser20/PR_TEST pull request #4
Opened 2017-07-06 14:34 UTC by githubTestUser21

This functionality is supper fancy and you won't believe how cool it is. 🖖

2017-07-06 15:27 UTC, githubTestUser20 requested changes

2017-07-06 15:27 UTC, githubTestUser20 commented on component/input/index.js
> +    return (IDoSomethingSuperFancyHere(1, 4)) * 5
Methods names start with lowercase

2017-07-06 15:27 UTC, githubTestUser20 commented on component/input/index.js
> +    return (y + x ) * 5
A `;` is missing at the end of this line.

2017-07-07 12:04 UTC, githubTestUser20 requested changes
Please do the requested changes.

2017-07-07 12:04 UTC, githubTestUser20 commented on component/input/index.js
> +    return (IDoSomethingSuperFancyHere(1, 4)) * 5 * 5;
Please the function name should start with lowerCase

2017-07-07 12:19 UTC, githubTestUser20 approved these changes

2017-07-07 12:22 UTC, githubTestUser20 commented on component/input/index.js
> +function iDoSomethingSuperFancyHere(x, y) {
I'd like some indentation here, but, don't do int now.

2017-07-07 12:23 UTC, githubTestUser21 commented on component/input/index.js
> +function iDoSomethingSuperFancyHere(x, y) {
Ok, next time I'll do it.

2017-07-07 12:24 UTC, githubTestUser20 submitted a review, later dismissed

2017-07-07 12:24 UTC, githubTestUser20 commented on component/input/index.js
> +    return (iDoSomethingSuperFancyHere(1, 4)) * 5 * 5;
I just realised the 5 should be 5.1

2017-07-07 12:26 UTC, githubTestUser21 commented on component/input/index.js
> +    return (iDoSomethingSuperFancyHere(1, 4)) * 5 * 5;
No, you are wrong. It has to be `5`.

2017-07-07 12:27 UTC, githubTestUser20 commented on component/input/index.js
> +    return (iDoSomethingSuperFancyHere(1, 4)) * 5 * 5;
Ok, you are right. I'll dismiss the review.

2017-07-07 12:29 UTC, githubTestUser20 approved these changes
Ok for me, after double check. I'll approve it.

2017-07-07 13:13 UTC, githubTestUser20 reviewed
Let's do a meeting about this changes.

2017-07-07 13:14 UTC, githubTestUser20 requested changes

2017-07-07 13:14 UTC, githubTestUser20 commented on component/input/index.js
> +function iDoSomethingSuperFancyHere(x, y) {
I just noticed the variables are to small.

2017-07-07 13:31 UTC, githubTestUser20 approved these changes

2017-07-07 13:31 UTC, githubTestUser20 commented on component/input/index.js
> +    return (totalA + totalB ) * 5;
The number `5` is risky, but Ok !.

2017-07-07 13:36 UTC, merged